build_requires: {}
conflicts: {}
dist_name: biber-linux_x86_64
distribution_type: par
dynamic_config: 0
generated_by: 'PAR::Packer version 1.024
license: unknown
par:
  clean: 0
  signature: ''
  verbatim: 1
  version: 1.007
